### ISSUE TITLE
Overlord Spawner

### ISSUE THREAD

**Issue by roedar** [UO-Eclipse/Ultima-Eclipse#10]
Missing overlord spawns -> Khaldun / Despise / Ankh / Blood / Exodus / Rock / Sorcerers / Spectre / Wisp.
_Additionally; could remove a few of these considering so many were in place to avoid constant crying from PvP, but then would have to remove and then probably re-imburse for the lost ones_

**Comment by Kalan-Brock** [comment]
@roedar 

Still working on these, but wanted to mention - Ankh dungeon's altar was placed some days ago.
