### ISSUE TITLE
Protection Spell

### ISSUE THREAD

**Issue by discostu2u** [UO-Eclipse/Ultima-Eclipse#12]
Upon death the buff does not wear off, but it does disappear from the buffs window.  Persistence through death is per UOguide, but the buff should also show in the buffs window after dying.  This would also apply to Reactive Armor and Magic Reflection.  Though not tested, the same mechanics are at work and likely become 'invisible' buffs upon dying.

**Comment by Kalan-Brock** [comment]
@discostu2u This should be fixed for restart.  After restart, you may need to cast off, then retoggle it.  Thank you!
