### ISSUE TITLE
Nightmare spawn

### ISSUE THREAD

**Issue by discostu2u** [UO-Eclipse/Ultima-Eclipse#20]
Missing one spawn location: Corrupted Forest east of Umbra.  Since there is no Felucca, that leaves just one spawn location.

More pressing, they're currently only spawning as a 3-slot pet when there should be a 30% chance to spawn as a 2-slot pet with reduced STR range 251-319.

**Comment by Kalan-Brock** [comment]
There are approximately 23 nightmare spawns in our world, it's quite custom.  I've fixed the control slot minimum issue on them for restart.
