### ISSUE TITLE
House Editing

### ISSUE THREAD

**Issue by roedar** [UO-Eclipse/Ultima-Eclipse#24]
House editing with the Eclipse launcher is pretty wonky. Noticeably going up floors, placing tiles on north and west sides (like fences), and the toggle walls/floors options of other floors.

**Comment by Kalan-Brock** [comment]
@roedar

Actually not a launcher issue, but rather a ClassicUO issue.  May need to submit a ticket with them to update the client, then I can pull their update(s) in after the fact and trigger an update via the launcher.  You can find their information here - https://github.com/ClassicUO/ClassicUO
