### ISSUE TITLE
Dreadhorn Corpse Timer

### ISSUE THREAD

**Issue by gonculator** [UO-Eclipse/Ultima-Eclipse#31]
[grab doesnt get what I want from a peerless corpse. It's a complicated corpse to loot but decays in ~5 mins, too fast to loot stuff at the bottom. Can this timer (and likely all peerless boss corpses) be increased to something like 7 or 8 mins, or maybe 2 mins longer than whatever it is?

**Comment by Kalan-Brock** [comment]
Peerless corpses will take 5 minutes longer to decay than a normal corpse after next restart.
