### ISSUE TITLE
Queen's Loyalty and Ter Mur house placement

### ISSUE THREAD

**Issue by discostu2u** [UO-Eclipse/Ultima-Eclipse#35]
Currently there is no way to see your loyalty rating in order to be able to use the queen's soulforge (has bonus) and place houses in Ter Mur.  Normally, there is a Loyalty listing in the player's context menu (click-self) which also includes things like fame and karma.  Since these other ratings are fitted into [mystats, I think queen's loyalty should also be included in that, unless you're going to use the whole city loyalty thing (players become governers, city buffs granted, etc) in which case you'd probably wanna keep all of that in a separate menu like the current system on Broadsword (OSI).

**Comment by Kalan-Brock** [comment]
Queens Loyalty will no longer be needed to place houses in TerMur or to use the Queen's Soul Forge - after next restart.
