### ISSUE TITLE
Spawn in Blood Dungeon

### ISSUE THREAD

**Issue by gonculator** [UO-Eclipse/Ultima-Eclipse#43]
Seems like blood elementals and imps are spawning in weird areas outside map. Sometimes you can still see them and cast, but hard to sampire or pet dmg or loot.

![image](https://user-images.githubusercontent.com/99579143/155268979-5acf944c-c03d-441f-a548-4ee8d215c7fa.png)

**Comment by discostu2u** [comment]
On Atlantic, they allow Thunderstorm to penetrate through walls for handling this.  Easier than getting paged every time this happens than to fix every tile on the map.  Perhaps something like that could be implemented here.

**Comment by Kalan-Brock** [comment]
@gonculator @discostu2u This has been corrected, thanks!
