### ISSUE TITLE
Auction House

### ISSUE THREAD

**Issue by discostu2u** [UO-Eclipse/Ultima-Eclipse#44]
A 'buy now' option is available to the seller, but there is no button for buyers to utilize this and be able to buy out an item.

**Comment by Kalan-Brock** [comment]
@discostu2u This is intentional.  The buy/bid buttons won't show to the person that listed the auction, as they won't be bidding on their own items.  Try on another character.

**Comment by discostu2u** [comment]
Actually, I tested this on another character.  It does not show for the other character.
