### ISSUE TITLE
Request - not issue

### ISSUE THREAD

**Issue by gonculator** [UO-Eclipse/Ultima-Eclipse#48]
Request to see system message when the server has crashed or is otherwise planned to reboot. It's nice to know in the journal that there was a server issue and not perform a bunch of network testing. If this were implemented and no msg in journal I can safely assume it's my end. Just a suggestion, I'm open to counter suggestions.

**Comment by Kalan-Brock** [comment]
@gonculator goingsolo and I just discussed this in person.  I'll soon be working on a public notice system.  Thanks!
