### ISSUE TITLE
Shimmering Effusion

### ISSUE THREAD

**Issue by gonculator** [UO-Eclipse/Ultima-Eclipse#51]
Looks like the keys are not dropping from anything except unfrozen mummies. Or if they are spawning, the mob respawn rate is way too slow so you can't obtain keys in many hours of waiting for mobs to spawn. Maybe just turn up the respawn rate to see if keys are spawning. But noted earlier, keys are dropping normally on the unfrozen mummies.

**Comment by Kalan-Brock** [comment]
Drops have been heavily increased for next restart.
