### ISSUE TITLE
Tinker NPCs

### ISSUE THREAD

**Issue by discostu2u** [UO-Eclipse/Ultima-Eclipse#6]
With the tinkering bod system more tinker npcs were added to every city including Umbra (at the provisioner), Moonglow (at the bank) among others to facilitate the bribery system.  The issue is more pressing due to the absence of a Felucca facet, thus already halving the number of npc’s.

**Comment by Kalan-Brock** [comment]
More Tinkers have been added to the locations mentioned, also more placed in Britain.
