### ISSUE TITLE
Crystal of Enhancement

### ISSUE THREAD

**Issue by roedar** [UO-Eclipse/Ultima-Eclipse#70]
Can't apply +Stealing to Burglar's Bandana despite the crystal saying it works on armor. Assuming possibly a clothing piece doesn't count as "armor" since a lot of the cloth items/relics can't go into the armor storage key being classified as a cloth item.

**Comment by discostu2u** [comment]
Good instincts on this.  I think Burglar's Bandana is normally seen by the game as armor, ie, when using Potion of Transmogrification, but since Enhancement Crystals are a custom, they might not read the item the same way.
