### ISSUE TITLE
Invasion Spellbooks

### ISSUE THREAD

**Issue by discostu2u** [UO-Eclipse/Ultima-Eclipse#74]
Not blessed, can't insure.  Not sure how you wanna resolve this.  As in, if you bless them, will they fall to the invader's corpse?  Anyway, thanks.

**Comment by Kalan-Brock** [comment]
Fixed for restart.  As for the dropping on the corpse, this actually gets added to the corpse after the creatures death, so being blessed will not affect the drop at all.
