### ISSUE TITLE
Pet Control Slots

### ISSUE THREAD

**Issue by discostu2u** [UO-Eclipse/Ultima-Eclipse#81]
Reopening this issue as it was fixed and then reverted after the following restart (awhile back), but also to include dragons.  White Wyrms and Dragons are supposed to spawn as 3slots, but they're all spawning 4, which makes them useless for training and impossible for pet combinations.  Nightmares are supposed to spawn as 2-slot 33% of the time, but the rate for 2-slots here are a lot lower as I've tamed close to a hundred and only have three of them be 2-slotted.  Since the custom invasions feature vanity-skinned nightmare pets, this should definitely be adjusted since no one can really use a 3 slot mare.  Finally, i'll also add that Greater Dragons have a rare chance (the number isn't nailed down yet, but stratics and uo-cah.com confirm) to spawn as a 4-slot.  I haven't had time to turn over enough of these to really test, but if and when this issue is addressed, please also look into the code to see if it's possible on Eclipse.  THANKS!

**Comment by Kalan-Brock** [comment]
This is addressed for our next restart.  Nightmares were set as a 3 slot min train, now set as 2.  Dragons and White Wyrms similarly had a min slot training set as 4, which has now been dropped to 3.
