### ISSUE TITLE
Maritime Cargo Drops

### ISSUE THREAD

**Issue by gonculator** [UO-Eclipse/Ultima-Eclipse#82]
Beacons aren't dropping cargo 100% of the time, as they should. I believe they should always drop Mythical quality for beacons and usually lower quality for other spawn nearby. Sea Serps, Deep Sea Serps, and Water Eles are all (rarely) dropping cargo as expected.

**Comment by discostu2u** [comment]
How about pirates?  There ought to be a better chance for drops (and usually higher quality) on these than serpents/eles, though not 100% like beacons.

**Comment by gonculator** [comment]
Actually, serps and other spawn don't seem to be dropping chests. Only the orcs on the beacon drop one or two each time you clear the ship. I have not seen any other ships out there, just the beacons. But to fair I've only said Tok and I think pirates might spawn near minoc or something.

**Comment by Kalan-Brock** [comment]
Increased cargo drops, and now beacons will drop every time.  Changes going in at next restart.
